# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_3d_2": "00_core.ipynb",
         "normalizePatches": "00_core.ipynb",
         "len_multiple_32": "00_core.ipynb",
         "mse_masked": "00_core.ipynb",
         "mse_masked_loss": "00_core.ipynb",
         "read_covid_CT_and_mask": "00_core.ipynb",
         "normalize_rotate": "00_core.ipynb",
         "pad_volume_to_multiple_32": "00_core.ipynb",
         "choose_loss": "00_core.ipynb",
         "plot_4_inpaints": "00_core.ipynb",
         "unet5": "01_unets.ipynb"}

modules = ["core.py",
           "unets.py"]

doc_url = "https://fastai.github.io/inpaint_covid/"

git_url = "https://github.com/fastai/inpaint_covid/tree/master/"

def custom_doc_links(name): return None
